# Generated by Django 3.0.4 on 2020-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorapp', '0003_register_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register_table',
            options={'verbose_name_plural': 'Register Table'},
        ),
        migrations.AddField(
            model_name='register_table',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='register_table',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
