# Generated by Django 3.0.4 on 2020-05-02 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majorapp', '0006_add_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250)),
                ('property_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('property_image', models.ImageField(upload_to='products')),
                ('details', models.TextField()),
                ('property_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majorapp.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
