# Generated by Django 3.0.4 on 2020-05-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majorapp', '0007_add_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_product',
        ),
    ]
